pragma Singleton
import QtQuick
import Quickshell

// Static palette. This used to be wallpaper-dynamic, re-generated by
// wallust on every wallpaper change and hot-reloaded via FileView. That
// dependency has been removed for portability -- this file now just
// exposes a fixed set of colors under the same property names, so every
// panel/service that references Colors.background / Colors.colorN keeps
// working unchanged.
//
// To make this dynamic again (e.g. wire your own theme generator), swap
// the property values below for a FileView + JsonAdapter reading a JSON
// file of your choice, keeping the same property names.
Item {
    id: root

    readonly property string background: "#1a1b26"
    readonly property string foreground: "#c0caf5"
    readonly property string color0:  "#1a1b26"
    readonly property string color1:  "#f7768e"
    readonly property string color2:  "#9ece6a"
    readonly property string color3:  "#e0af68"
    readonly property string color4:  "#7aa2f7"
    readonly property string color5:  "#bb9af7"
    readonly property string color6:  "#7dcfff"
    readonly property string color7:  "#a9b1d6"
    readonly property string color8:  "#414868"
    readonly property string color9:  "#f7768e"
    readonly property string color10: "#9ece6a"
    readonly property string color11: "#e0af68"
    readonly property string color12: "#7aa2f7"
    readonly property string color13: "#bb9af7"
    readonly property string color14: "#7dcfff"
    readonly property string color15: "#c0caf5"

    // Semantic aliases, same 6-hue-family plan used in nvim/btop (each
    // hue ~60 degrees apart so metrics read as genuinely different colors,
    // not just different brightnesses of the same one). `critical` in
    // particular exists so "this value is dangerously high" always means
    // the same universal red across every panel, instead of some widgets
    // using neutral foreground for their most alarming state (which reads
    // as calm, not urgent -- backwards).
    readonly property string critical: adapter.color9
}

